### ISSUE TITLE
Error message under Post Type

### ISSUE THREAD

**Issue by ciptard** [adampatterson/Tentacle#46]
I've installed Tentacle on my local server and found this error message under "Post Type" when trying to add new post:

```Notice: Undefined variable: template In C:\xampp\htdocs\tentaclecms\application\helper\theme.php At Line 134

Warning: Invalid argument supplied for foreach() In C:\xampp\htdocs\tentaclecms\application\view\admin\content\content_add_post.php At Line 44

```
```

**Comment by adampatterson** [comment]
Hello ciptard,

If you were able to get to that point then you were successful! :)

Soon I will be testing the creation of content, Themes exist but are not functional as in they dont display content.

I will take a look and what might cause this error so that it can be fixed for the next test.

Thanks

**Comment by ciptard** [comment]
thank you.
I hope I can be a beta tester, I found it really easy to use and.... it's just awesome!

**Comment by adampatterson** [comment]
Glad to hear it!

**Comment by adampatterson** [comment]
This should be fixed with the latest dev version.

I have added some seed data on the install as well as front end templates.

Tested locally as well as on an LAMP server.
